spring:
  # DB
  datasource:
    username:
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework.security: INFO