spring:
  config:
    activate:
      on-profile: dev //dev

  application:
    name: oauth

  data:
    mongodb:
      uri: mongodb+srv://atlas_user:atlas123@mycluster.qjupvtn.mongodb.net/oauthdb1?retryWrites=true&w=majority

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  # ?? ?? Client ID
            client-secret:  # ?? ?? Client Secret
            scope: openid, email, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  # MongoDB 쿼리 로그 보기

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # ? ??

oauth:
  google:
    client-id:  # ?? ?? Client ID
    client-secret:  # ?? ?? Client Secret
    redirect-uri: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id:  # ?? ?? Client ID
    client-secret:  # ?? ?? Client Secret
    redirect-uri: http://localhost:3000/oauth/kakao/redirect