spring:
  config:
    activate:
      on-profile: prod

  application:
    name: oauth

  data:
    mongodb:
      uri: mongodb://admin:homeprotector2025!@10.0.51.19:27017/homeprotector?authSource=admin
      # 연결 풀 설정
      options:
        max-connection-pool-size: 100
        min-connection-pool-size: 10
        max-connection-idle-time: 30000
        max-connection-life-time: 600000
        connect-timeout: 10000
        socket-timeout: 45000
        server-selection-timeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 24685883095-m1obadjrnp9hdo6gs16sae9n89gmqklq.apps.googleusercontent.com # ?? ?? Client ID
            client-secret: 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 # ?? ?? Client Secret
            scope: openid, email, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG  # MongoDB 쿼리 로그 보기

jwt:
  secret: b2F1dGhzZXJ2ZXJzZWNyZXRhY2Nlc3N0b2tlbm9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW9hdXRoc2VydmVyc2VjcmV0YWNjZXNzdG9rZW5vYXV0aHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000

oauth:
  google:
    client-id: 24685883095-m1obadjrnp9hdo6gs16sae9n89gmqklq.apps.googleusercontent.com # ?? ?? Client ID
    client-secret: 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 # ?? ?? Client Secret
    redirect-uri: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id: 1fd78124bd0e821625d4167a3bc8c59f # ?? ?? Client ID
    client-secret: 2j2ADZmKMuTvOaljgkEoCCbkgrsUngwx # ?? ?? Client Secret
    redirect-uri: http://localhost:3000/oauth/kakao/redirect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
