name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ secrets.DOCKER_IMAGE }}
          cache-from: type=gha # gha = Github Actions
          cache-to: type=gha,mode=max

      - name: Pull from docker hub and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USERNAME }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd /home/***/
            export KUBECONFIG="kubeconfig-homeprotector.yaml"

            # 배포
            kubectl apply -f ${{ secrets.DOCKER_REPOSITORY }}.yml
            # 배포 상태 확인
            kubectl rollout status deployment/${{ secrets.DOCKER_REPOSITORY }}

            # 서비스 상태 확인
            kubectl get service ${{ secrets.DOCKER_REPOSITORY }}
            kubectl get pods -l app=${{ secrets.DOCKER_REPOSITORY }}
